[local]
localhost ansible_connection=local

[tradelive]
tradelive-vm ansible_host=192.168.121.140 ansible_port=22 ansible_user=vagrant ansible_ssh_private_key_file=/home/aiml_323103382064/devops-lab/vagrant-vm/.vagrant/machines/default/libvirt/private_key

